//@ui5-bundle customer/ravisoni/sapfioritools/Component-preload.js
sap.ui.require.preload({
	"customer/ravisoni/sapfioritools/Component.js":function(){
sap.ui.define(["sap/ui/core/UIComponent","customer/ravisoni/sapfioritools/model/models"],(e,i)=>{"use strict";return e.extend("customer.ravisoni.sapfioritools.Component",{metadata:{manifest:"json",interfaces:["sap.ui.core.IAsyncContentCreation"]},init(){e.prototype.init.apply(this,arguments);this.setModel(i.createDeviceModel(),"device");this.getRouter().initialize()}})});
},
	"customer/ravisoni/sapfioritools/controller/App.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],o=>{"use strict";return o.extend("customer.ravisoni.sapfioritools.controller.App",{onInit(){}})});
},
	"customer/ravisoni/sapfioritools/controller/View1.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],(t,i)=>{"use strict";return t.extend("customer.ravisoni.sapfioritools.controller.View1",{onInit(){var t={items:[{title:"Grid item title 1",subtitle:"Subtitle 1"},{title:"Grid item title 2",subtitle:"Subtitle 2"},{title:"Grid item title 3",subtitle:"Subtitle 3"},{title:"Grid item title 4",subtitle:"Subtitle 4"},{title:"Grid item title 5",subtitle:"Subtitle 5"},{title:"Grid item title 6 Grid item title Grid item title Grid item title Grid item title Grid item title",subtitle:"Subtitle 6"},{title:"Very long Grid item title that should wrap 7",subtitle:"This is a long subtitle 7"},{title:"Grid item title B 8",subtitle:"Subtitle 8"},{title:"Grid item title B 9 Grid item title B  Grid item title B 9 Grid item title B 9Grid item title B 9title B 9 Grid item title B 9Grid item title B",subtitle:"Subtitle 9"},{title:"Grid item title B 10",subtitle:"Subtitle 10"},{title:"Grid item title B 11",subtitle:"Subtitle 11"},{title:"Grid item title B 12",subtitle:"Subtitle 12"},{title:"Grid item title 13",subtitle:"Subtitle 13"},{title:"Grid item title 14",subtitle:"Subtitle 14"},{title:"Grid item title 15",subtitle:"Subtitle 15"},{title:"Grid item title 16",subtitle:"Subtitle 16"},{title:"Grid item title 17",subtitle:"Subtitle 17"},{title:"Grid item title 18",subtitle:"Subtitle 18"},{title:"Very long Grid item title that should wrap 19",subtitle:"This is a long subtitle 19"},{title:"Grid item title B 20",subtitle:"Subtitle 20"},{title:"Grid item title B 21",subtitle:"Subtitle 21"},{title:"Grid item title B 22",subtitle:"Subtitle 22"},{title:"Grid item title B 23",subtitle:"Subtitle 23"},{title:"Grid item title B 24",subtitle:"Subtitle 24"},{title:"Grid item title B 21",subtitle:"Subtitle 21"},{title:"Grid item title B 22",subtitle:"Subtitle 22"},{title:"Grid item title B 23",subtitle:"Subtitle 23"}]};var e=new i(t);this.getView().setModel(e)}})});
},
	"customer/ravisoni/sapfioritools/i18n/i18n.properties":'# This is the resource bundle for customer.ravisoni.sapfioritools\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=App Title\n\n#YDES: Application description\nappDescription=An SAP Fiori application.\n#XTIT: Main view title\ntitle=App Title',
	"customer/ravisoni/sapfioritools/i18n/i18n_en.properties":'# This is the resource bundle for customer.ravisoni.sapfioritools\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=App Title\n\n#YDES: Application description\nappDescription=An SAP Fiori application.\n#XTIT: Main view title\ntitle=App Title',
	"customer/ravisoni/sapfioritools/i18n/i18n_en_US.properties":'# This is the resource bundle for customer.ravisoni.sapfioritools\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=App Title\n\n#YDES: Application description\nappDescription=An SAP Fiori application.\n#XTIT: Main view title\ntitle=App Title',
	"customer/ravisoni/sapfioritools/manifest.json":'{"_version":"1.65.0","sap.app":{"id":"customer.ravisoni.sapfioritools","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.17.3","toolsId":"b98a5e3c-b722-493b-9267-76690e4fbed0"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.134.1","libs":{"sap.m":{},"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"customer.ravisoni.sapfioritools.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","controlAggregation":"pages","controlId":"app","transition":"slide","type":"View","viewType":"XML","path":"customer.ravisoni.sapfioritools.view","async":true,"viewPath":"customer.ravisoni.sapfioritools.view"},"routes":[{"name":"RouteView1","pattern":":?query:","target":["TargetView1"]}],"targets":{"TargetView1":{"id":"View1","name":"View1"}}},"rootView":{"viewName":"customer.ravisoni.sapfioritools.view.App","type":"XML","id":"App","async":true}}}',
	"customer/ravisoni/sapfioritools/model/models.js":function(){
sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"customer/ravisoni/sapfioritools/view/App.view.xml":'<mvc:View controllerName="customer.ravisoni.sapfioritools.controller.App"\n    displayBlock="true"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"><App id="app"></App></mvc:View>',
	"customer/ravisoni/sapfioritools/view/View1.view.xml":'<mvc:View controllerName="customer.ravisoni.sapfioritools.controller.View1"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns:f="sap.f"\n    xmlns="sap.m"><Page id="page" title="{i18n>title}"><f:GridList\n\t\t\tid="gridList"\n\t\t\theaderText="GridList header"\n\t\t\titems="{/items}"><f:GridListItem><VBox class="sapUiSmallMargin"><layoutData><FlexItemData growFactor="1" shrinkFactor="0" /></layoutData><Title text="{title}" wrapping="true" /><Label text="{subtitle}" wrapping="true" /></VBox></f:GridListItem></f:GridList></Page></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
